---
development:
  cloud_name: dvizsamps
  api_key: <%= Rails.application.credentials.cloudinary_id %>
  api_secret: <%= Rails.application.credentials.cloudinary_secret %>
  enhance_image_tag: true
  static_image_support: false
  secure: true
production:
  cloud_name: dvizsamps
  api_key: <%= Rails.application.credentials.cloudinary_id %>
  api_secret: <%= Rails.application.credentials.cloudinary_secret %>
  enhance_image_tag: true
  static_image_support: true
  secure: true
test:
  cloud_name: dvizsamps
  api_key: <%= Rails.application.credentials.cloudinary_id %>
  api_secret: <%= Rails.application.credentials.cloudinary_secret %>
  enhance_image_tag: true
  static_image_support: false
  secure: true
