
# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon_dev:
  service: S3
  access_key_id: <%= ENV['EMBEDS_AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['EMBEDS_AWS_SECRET_ACCESS_KEY'] %>
  region: us-west-1
  bucket: browzable-movie-posters

amazon_prod:
  service: S3
  access_key_id: <%= ENV['EMBEDS_AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['EMBEDS_AWS_SECRET_ACCESS_KEY'] %>
  region: us-west-1
  bucket: browzable-movie-posters

