amazon_dev:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws_storage_access_key_id %>
  secret_access_key: <%= Rails.application.credentials.aws_storage_secret_access_key %>
  region: us-west-1
  bucket: browzable-movie-posters

amazon_prod:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws_storage_access_key_id %>
  secret_access_key: <%= Rails.application.credentials.aws_storage_secret_access_key %>
  region: us-west-1
  bucket: browzable-movie-posters

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws_storage_access_key_id %>
  secret_access_key: <%= Rails.application.credentials.aws_storage_secret_access_key %>
  region: us-west-1
  bucket: browzable
